### ISSUE TITLE
Bug: Do not display text

### ISSUE THREAD

**Issue by ssr123456789** [mustafa1dev/TeleVip-Lsposed#1]
Telegram：org.telegram.messenger
Version 11.5.3(55119)
![Screenshot_2024-12-08-06-42-06-37_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/53d47d96-d458-4f76-a91f-4fb64b59ca75)

**Comment by mustafa1dev** [comment]
Thank you for your suggestion regarding the issue.
The problem has been resolved, and now you can use TeleVip without any issues.

**Comment by ssr123456789** [comment]
> 感谢您针对此问题提出的建议。 问题已解决，现在您可以毫无问题地使用 TeleVip。

Thank you. The problem has been solved. I have a request. I hope your module can support Nagram client.

**Comment by mustafa1dev** [comment]
Soon, I will make the module support multiple versions, including other variants like Nagram.
