### ISSUE TITLE
FR: Please add support exteraGram

### ISSUE THREAD

**Issue by bbppoo** [mustafa1dev/TeleVip-Lsposed#10]
Can you add support for the exteraGram client?
Package name `com.exteragram.messenger`
Official website: https://exteragram.app/
GitHub: https://github.com/exteraSquad/exteraGram
Although the release version has not been updated for a year, fortunately the beta version has not stopped updating so far, I like it.
exteraGram Beta: https://t.me/exteraGramCI

**Comment by mustafa1dev** [comment]
Support for the exteraGram client will be added in a new update of TeleVip

**Comment by bbppoo** [comment]
Thank u

**Comment by bbppoo** [comment]
> Support for the exteraGram client will be added in a new update of TeleVip

The exteraGram release has been updated to version 11.5.3 (55119). Can you adapt it in the next version? Thank u very much

**Comment by mustafa1dev** [comment]
Thank you for notifying me, and ExteraGram will be updated to version 11.5.3 in a new on update.
