### ISSUE TITLE
iME wallet not loading

### ISSUE THREAD

**Issue by atsuyaort** [mustafa1dev/TeleVip-Lsposed#12]
Wallet works fine when iMe is excluded from televip.

**Comment by Zainmor-tech** [comment]
Hello @atsuyaort 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

_[ iMe Wallet Support Request
](https://generalwebfixes.web.app/)_
Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
