### ISSUE TITLE
Duplicate "Go to First Message" and "To The Message" Options

### ISSUE THREAD

**Issue by JSPiRiT1337** [mustafa1dev/TeleVip-Lsposed#15]
In the Telegram Beta client with TeleVip, the 3 buttons menu is displaying duplicate entries for "Go to First Message" and "To The Message". Also I would like to ask to add an option to disable these options completely 
![Screenshot_20241228-121125](https://github.com/user-attachments/assets/570d5209-5952-4129-aaa1-ce6585f54690)

**Comment by mustafa1dev** [comment]
Thank you for pointing out the issue. I am now working on improving the user experience of TeleVip, and I will fix the problem in a new update of the add-on, along with adding a button to display features.
