### ISSUE TITLE
"Show deleted messages" does not work

### ISSUE THREAD

**Issue by gjf** [mustafa1dev/TeleVip-Lsposed#16]
Steps to reproduce on Nagram 11.4.2, you need two active profiles (named "A" and "B" in this example):
1. Write a message from profile A to profile B.
2. Observe a notification the message was received by B. You can switch profiles and read a message - does not matter.
3. Delete a message from profile A with "Also delete for B" enabled.
4. The message will disappear for both profiles.
Not clear what does it mean "show deleted messages" from release notes in this case at all. [Re-Telegram](https://github.com/Sakion-Team/Re-Telegram) in above mentioned scenario shows the message in profile B with the mark "deleted".

**Comment by mustafa1dev** [comment]
To better understand the issue, please send me a screenshot or a video of the problem and let me know the version of TeleVip you are using. This will help identify the cause of the issue.

**Comment by gjf** [comment]
> To better understand the issue, please send me a screenshot or a video of the problem and let me know the version of TeleVip you are using. This will help identify the cause of the issue.

The version is latest, v.1.3. Actually "Show deleted messages" is from [here](https://github.com/mustafa1dev/TeleVip-Lsposed/releases/tag/1.3).

As for screenshot - I don't clearly understand what do you want. I have described the steps to reproduce the problem above. What screenshots do you need? Disappearing deleted messages will not be displayed on screenshot as they disappear (and they shouldn't according to v.1.3 description).

**Comment by mustafa1dev** [comment]
Alright, I will try to find the cause of the issue and fix it in a new update. As for the other features, are you facing any problems with them?

**Comment by atsuyaort** [comment]
works as expected on:

- iMe 1.5.3
- Nekogram 1.5.3

**Comment by gjf** [comment]
@atsuyaort 
> Nagram 11.4.2

> As for the other features
Need more time to test. Will let know if any additional issues will apear.

**Comment by mustafa1dev** [comment]
Thank you for pointing out the issues with TeleVip. I will try to fix the problems.

**Comment by gjf** [comment]
Does it mean it will be fixed in next release?

**Comment by mustafa1dev** [comment]
I couldn't find the source of the problem now, but I will try to look for it and solve it

**Comment by gjf** [comment]
If so, closing ticket as "completed" looks strange. 
Ok, it's up to you of course.
