### ISSUE TITLE
Detected as a Trojan - VT

### ISSUE THREAD

**Issue by pacmankillers** [mustafa1dev/TeleVip-Lsposed#2]
Hi Mustafa1dev

Thank you for this amazing module, I installed in two phones, one was good but second give me a warning about risks using Televip.

I verified on Virustotal and this is the result:

https://www.virustotal.com/gui/file/42af935526f8477ce5f7d3f046abf6d2c233353c51a0b6cb9ed09e1f32019b85/detection

8 AV detected as a trojan, facestealer and Keylogger.

I wrote this to help you if any person think is virus.

**Comment by mustafa1dev** [comment]
Thank you, I will try to remove all malware warnings and release a new update.
