### ISSUE TITLE
Hide online status

### ISSUE THREAD

**Issue by Chen-hai-0721** [mustafa1dev/TeleVip-Lsposed#5]
All Settings for Ghost Mode are turned on, but others can still click on my profile page to check my online status. Does the module not handle this

**Comment by mustafa1dev** [comment]
Hide online status will be added in an upcoming update.

**Comment by Chen-hai-0721** [comment]
When will the new update be released

**Comment by mustafa1dev** [comment]
Soon, almost less than a week.
