### ISSUE TITLE
Feature Request: Support Telegram Beta and Implement "Anti-Recall"

### ISSUE THREAD

**Issue by JSPiRiT1337** [mustafa1dev/TeleVip-Lsposed#9]
Hey! Currently, this module does not support the Telegram Beta application (package name: `org.telegram.messenger.beta`). That's sad. Additionally, there's a need for an "anti-recall" feature. Thank you!

**Comment by mustafa1dev** [comment]
I will make the feature support Telegram Beta.
Thank you for the suggestion
